Repository UNITHON-TEAM-3/Ditto-Letto, pull requests merged in 2023-09, with the labels that each got.

#2 ⚙️ :: Tuist 세팅 완료
  .gitignore
  App/Derived/Sources/TuistAssets+DittoLetto.swift
  App/Derived/Sources/TuistBundle+DittoLetto.swift
  App/Project.swift
  App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  App/Resources/Assets.xcassets/Contents.json
  App/Resources/LaunchScreen.storyboard
  App/Sources/AppDelegate.swift
  App/Sources/SceneDelegate.swift
  App/Support/Info.plist
  Derived/InfoPlists/DittoLetto-Info.plist
  Derived/InfoPlists/DittoLettoKit-Info.plist
  Derived/InfoPlists/DittoLettoKitTests-Info.plist
  Derived/InfoPlists/DittoLettoTests-Info.plist
  Derived/InfoPlists/DittoLettoUI-Info.plist
  Derived/InfoPlists/DittoLettoUITests-Info.plist
  Derived/Sources/TuistBundle+DittoLetto.swift
  Makefile
  README.md
  ThirdPartyLib/Derived/InfoPlists/ThirdPartyLib-Info.plist
  ThirdPartyLib/Project.swift
  ThirdPartyLib/Sources/Project.swift
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Executable.swift
  Tuist/ProjectDescriptionHelpers/OrganizationName.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  Tuist/ProjectDescriptionHelpers/TargetScript.swift
  Workspace.swift
Labels: setting

#11 카카오 소셜 로그인 & 토큰 Scene 토큰 저장
  App/Derived/Sources/TuistAssets+DittoLetto.swift
  App/Resources/Image.xcassets/kakaoButton.imageset/Contents.json
  App/Resources/Image.xcassets/kakaoButton.imageset/kakaoButton.svg
  App/Resources/Image.xcassets/loginImage.imageset/Contents.json
  App/Resources/Image.xcassets/loginImage.imageset/concept image.svg
  App/Resources/Image.xcassets/lunchImage .imageset/Contents.json
  App/Resources/Image.xcassets/lunchImage .imageset/lunchImage.svg
  App/Sources/App/AppDelegate.swift
  App/Sources/App/SceneDelegate.swift
  App/Sources/Model/TokenModel.swift
  App/Sources/Networking/Client.swift
  App/Sources/Networking/Service.swift
  App/Sources/Scene/Login/LoginVC.swift
  App/Sources/Scene/Login/LoginVM.swift
  App/Support/Info.plist
Labels: feature

#15 홈 API 연결
  App/Derived/Sources/TuistAssets+DittoLetto.swift
  App/Derived/Sources/TuistBundle+DittoLetto.swift
  App/Derived/Sources/TuistFonts+DittoLetto.swift
  App/Resources/Image.xcassets/state07.imageset/Contents.json
  App/Resources/Image.xcassets/state07.imageset/Progressbar 7.svg
  App/Sources/Extension/HomeEmptyView.swift
  App/Sources/Extension/HomeTableHeaderView.swift
  App/Sources/Extension/HomeTableViewCell.swift
  App/Sources/Extension/MyLetterCircleView.swift
  App/Sources/Extension/MyLetterView.swift
  App/Sources/Model/LetterMyModel.swift
  App/Sources/Networking/Client.swift
  App/Sources/Networking/Service.swift
  App/Sources/Scene/Login/LoginVM.swift
  App/Sources/Scene/MyLetters/HomeModel.swift
  App/Sources/Scene/MyLetters/MyLetterVM.swift
  App/Sources/Scene/MyLetters/MyLettersVC.swift
Labels: feature

#17 편지 전달 완료 화면 & 보관함 화면 일부 구현
  App/Sources/Extension/KeepingLetterView.swift
  App/Sources/Scene/KeepingMyLetter/KeepingMyLetter.swift
  App/Sources/Scene/LoadingLetter/LoadingLetterVC.swift
  App/Sources/Scene/LoadingLetter/LoadingLetterVM.swift
  App/Sources/Scene/MyLetters/MyLetterVM.swift
  App/Sources/Scene/MyLetters/MyLettersVC.swift
Labels: UI
